---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "fabra-sync"
  namespace: "default"
  labels:
    app: "fabra-sync"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "fabra-sync"
  template:
    metadata:
      labels:
        app: "fabra-sync"
    spec:
      # 12 hour grace period to allow running replication activities to complete
      terminationGracePeriodSeconds: 43200
      containers:
      - name: "fabra-sync"
        image: "us-docker.pkg.dev/fabra-344902/fabra-sync/sync:latest"
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
            ephemeral-storage: "1Gi"
        env:
        - name: IS_PROD
          value: "true"
        - name: DB_USER
          value: "db_user"
        - name: DB_NAME
          value: "fabra-db"
        - name: DB_HOST
          value: "10.111.1.3"
        - name: DB_PORT
          value: "5432"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "fabra-sync-hpa-aykx"
  namespace: "default"
  labels:
    app: "fabra-sync"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "fabra-sync"
    apiVersion: "apps/v1"
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations:
    iam.gke.io/gcp-service-account: "fabra-sync@fabra-344902.iam.gserviceaccount.com"
  name: "default"
  namespace: "default"
