version: '3.1'

services:
  fabra_db:
    image: postgres
    volumes:
      - ./certs:/var/lib/postgresql/certs
      - ./init_fabra.sql:/docker-entrypoint-initdb.d/init_fabra.sql
      - ./init_source.sql:/docker-entrypoint-initdb.d/init_source.sql
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    command: postgres -c ssl=on -c ssl_cert_file=/var/lib/postgresql/certs/server.crt -c ssl_key_file=/var/lib/postgresql/certs/server.key

volumes:
  dbdata:
