steps:
- id: tf-init
  name: hashicorp/terraform:1.0.0
  entrypoint: sh
  dir: 'infra/terraform'
  args:
  - '-c'
  - 'terraform init'

- id: tf-plan
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: sh
  dir: 'infra/terraform'
  args:
  - '-c'
  - 'terraform plan'
  waitFor: ['tf-init']

- id: tf-apply
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: sh
  dir: 'infra/terraform'
  args:
  - '-c'
  - 'terraform apply -auto-approve'
  waitFor: ['tf-plan']
